### ISSUE TITLE
GHC type level literals support

### ISSUE THREAD

**Issue by l29ah** [Shimuuar/fixed-vector#7]
It would make producing type signatures a lot simpler. Otherwise it's sad you don't use type-natural as one would be able to use https://hackage.haskell.org/package/type-natural-0.2.3.2/docs/Data-Type-Natural.html#g:7 TH functions to simplify the task.

**Comment by Shimuuar** [comment]
Alas it's not possible to write inductive proofs for type level naturals (as of GHC 7.10) and this library is built around such proofs. So until ability write such proofs is added library is  stuck with Peano numerals

**Comment by l29ah** [comment]
How do i produce a type for a vector of 50 w/o using an ad hoc recursive code generator then?

**Comment by Shimuuar** [comment]
There's type familly for conversion from type level nats to Peano numbers: `Data.Vector.Fixed.Cont.ToPeano` which is useful in such situations:

```
> import Data.Vector.Fixed as F
> import Data.Vector.Fixed.Cont (ToPeano(..))
> import Data.Vector.Fixed.Boxed as V
> F.fromList [1..10] :: V.Vec (ToPeano 10) Int
fromList [1,2,3,4,5,6,7,8,9,10
```

Although it's not necessary good idea to create 50-element vector using this library. Since library uses Church encoding of vectors internally it means that GCH will have to manipulate 50-ary functions. I'm not sure it will be able to optimize them well and complie time will sure suffer

**Comment by l29ah** [comment]
Thank you, it worked, although ghc-7.10.2 crashed when it tried to compile it. runhaskell and ghci worked fine tho and this is enough for me. Type error messages were quite unreadable tho. Also it's fun that ghc can't deal with tuples longer than 62.
